//
// This file was generated by the JPA Modeler
//
package com.eshop.cart.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.ws.rs.FormParam;

@Entity
public class Customer implements Serializable {

    @Id
    @FormParam("id")
    private Long id;

    @Column(name = "FNAME")
    @Basic
    @NotNull
    @Size(min = 5, max = 50, message = "User's first name must contain between 5 and 50 characters")
    @FormParam("firstName")
    private String firstName;

    @Column(name = "LNAME")
    @Basic
    @FormParam("lastName")
    private String lastName;

    @Basic
    @FormParam("age")
    private String age;

    @Basic
    @FormParam("address")
    private String address;

    @Basic
    @FormParam("mobileNumber")
    private String mobileNumber;

    @OneToMany(targetEntity = ProductOrder.class)
    @JoinColumn(name = "CUSTOMER_ID")
    private List<ProductOrder> orders;

    public Customer() {

    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMobileNumber() {
        return this.mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public List<ProductOrder> getOrders() {
        return this.orders;
    }

    public void setOrders(List<ProductOrder> orders) {
        this.orders = orders;
    }
}
