//
// This file was generated by the JPA Modeler
//
package com.eshop.cart.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "PRO_ORDER")
public class ProductOrder implements Serializable {

    @Id
    @FormParam("id")
    private Long id;

    @Basic
    @FormParam("amount")
    private String amount;

    @Basic
    @FormParam("deliveryLocation")
    private String deliveryLocation;

    @Basic
    @FormParam("deliveryTime")
    private String deliveryTime;

    @Basic
    @FormParam("promoCode")
    private String promoCode;

    @ManyToMany(targetEntity = Product.class)
    @JoinTable(name = "PRODUCTORDER_PRODUCT")
    private List<Product> products;

    public ProductOrder() {

    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getDeliveryLocation() {
        return this.deliveryLocation;
    }

    public void setDeliveryLocation(String deliveryLocation) {
        this.deliveryLocation = deliveryLocation;
    }

    public String getDeliveryTime() {
        return this.deliveryTime;
    }

    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    public String getPromoCode() {
        return this.promoCode;
    }

    public void setPromoCode(String promoCode) {
        this.promoCode = promoCode;
    }

    public List<Product> getProducts() {
        return this.products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }
}
